# Generated by Django 4.2.7 on 2023-12-26 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0006_userfollows"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollows",
        ),
    ]
