# Generated by Django 4.2.7 on 2023-12-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0009_rename_follows_userfollows_contribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.CharField(
                blank=True, max_length=8192, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(blank=True, max_length=128, verbose_name="Titre"),
        ),
    ]
