# Generated by Django 4.2.7 on 2023-12-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0012_alter_review_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(blank=True, max_length=128, verbose_name="Titre"),
        ),
    ]
