# Generated by Django 4.2.7 on 2024-01-03 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0013_alter_review_headline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollows",
        ),
    ]
