# Generated by Django 4.2.7 on 2024-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0014_delete_userfollows"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="review_created",
            field=models.BooleanField(default=False),
        ),
    ]
