# Generated by Django 4.2.7 on 2023-12-18 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_user_follows"),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE authentication_user_follows;'),
    ]
