# Generated by Django 4.2.7 on 2023-12-18 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_auto_20231218_2128"),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE authentication_user_follows;'),
    ]
