# Generated by Django 4.2.7 on 2023-12-27 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_delete_userfollows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Personnes suivies",
            ),
        ),
    ]
