# Generated by Django 4.2.7 on 2023-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_alter_user_follows"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Photo de profil"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("CREATOR", "Créateur"), ("SUBSCRIBER", "Abonné")],
                max_length=30,
                null=True,
                verbose_name="Rôle",
            ),
        ),
    ]
