# Generated by Django 4.2.7 on 2024-01-03 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0015_alter_user_follows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
